# Generated by Django 4.2.2 on 2024-04-27 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Teststask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='teststask_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='teststask_details')),
                ('minutes', models.IntegerField(verbose_name='minutes')),
                ('limit', models.IntegerField(verbose_name='limit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teststask_category', to='guide.category')),
            ],
            options={
                'db_table': 'teststask',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
                ('reply1', models.TextField(verbose_name='reply1')),
                ('ok1', models.BooleanField(default=False, verbose_name='ok1')),
                ('reply2', models.TextField(verbose_name='reply2')),
                ('ok2', models.BooleanField(default=False, verbose_name='ok2')),
                ('reply3', models.TextField(blank=True, null=True, verbose_name='reply3')),
                ('ok3', models.BooleanField(default=False, verbose_name='ok3')),
                ('reply4', models.TextField(blank=True, null=True, verbose_name='reply4')),
                ('ok4', models.BooleanField(default=False, verbose_name='ok4')),
                ('reply5', models.TextField(blank=True, null=True, verbose_name='reply5')),
                ('ok5', models.BooleanField(default=False, verbose_name='ok5')),
                ('teststask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_teststask', to='guide.teststask')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datep', models.DateTimeField(auto_now_add=True, verbose_name='datep')),
                ('result', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='result')),
                ('details', models.TextField(blank=True, null=True, verbose_name='protocol_details')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='protocol_comment')),
                ('teststask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_teststask', to='guide.teststask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'protocol',
                'ordering': ['datep'],
            },
        ),
        migrations.AddIndex(
            model_name='teststask',
            index=models.Index(fields=['title'], name='teststask_title_5ed5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='protocol',
            index=models.Index(fields=['datep'], name='protocol_datep_b27e8d_idx'),
        ),
    ]
